name: Python package

on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"

jobs:
  test_github_action:
    name: "Just testing"
    runs-on: ubuntu-latest
    steps:
      - name: "List directory structure"
        run: ls

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8] # you can add more python version to test it in

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --cov-report html --cov=.
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: coverage-report
        path: htmlcov